import type { Metadata } from "next";
import ManagedImage from "@/components/ManagedImage";
import OrderOnlineButton from "@/components/OrderOnlineButton";
import Reveal from "@/components/Reveal";
import { bengaliImages } from "@/lib/site-content";

export const metadata: Metadata = { title: "About", description: "The Bengali Food serves authentic Bengali cuisine in the San Jose area." };

export default function AboutPage() {
  return <><section className="px-5 pb-16 pt-32 sm:px-6"><Reveal className="mx-auto grid max-w-6xl gap-10 lg:grid-cols-2 lg:items-center"><div><p className="text-xs font-black uppercase tracking-[.2em] text-primary">Our table</p><h1 className="mt-5 text-5xl font-black leading-[.94] text-secondary sm:text-7xl">Bengali food has a language of its own.</h1><p className="mt-6 text-lg leading-8 text-muted">Mustard, fish, lentils, seasonal vegetables, and carefully built spice are at the center of Bengali cooking. The Bengali Food brings those familiar flavors to the South Bay.</p><OrderOnlineButton className="mt-8 inline-flex min-h-12 items-center justify-center rounded-lg bg-primary px-7 text-sm font-black text-[#142016]" label="Explore the live menu" /></div><ManagedImage imageKey="Hero" fallback={bengaliImages.hero} alt="Bengali mustard prawn curry with rice and dal" width={1600} height={900} className="aspect-[4/3] w-full rounded-lg object-cover" /></Reveal></section><section className="border-y border-border bg-surface px-5 py-20 sm:px-6"><Reveal className="mx-auto max-w-6xl"><h2 className="text-4xl font-black text-secondary">Comfort in every course.</h2><div className="mt-8 grid gap-5 md:grid-cols-3"><p className="border-t border-border pt-4 text-muted"><strong className="text-secondary">Fish curries.</strong> Freshwater fish and seafood shine in mustard-forward gravies.</p><p className="border-t border-border pt-4 text-muted"><strong className="text-secondary">Vegetable dishes.</strong> Lentils, eggplant, and seasonal vegetables balance the table.</p><p className="border-t border-border pt-4 text-muted"><strong className="text-secondary">Shared meals.</strong> Dishes made for a comforting dinner or a special gathering.</p></div></Reveal></section></>;
}
