import type { Metadata } from "next";
import ManagedImage from "@/components/ManagedImage";
import ManagedMenuSections from "@/components/ManagedMenuSections";
import OrderOnlineButton from "@/components/OrderOnlineButton";
import Reveal from "@/components/Reveal";
import { menuCategories } from "@/lib/menu-data";
import { bengaliImages } from "@/lib/site-content";

export const metadata: Metadata = { title: "Menu", description: "Explore Bengali fish curries, seafood, lentils, and vegetarian classics from The Bengali Food." };

export default function MenuPage() {
  return <><section className="relative isolate overflow-hidden bg-[var(--kitchen-night)] px-5 pb-16 pt-28 text-white sm:px-6 lg:px-8"><ManagedImage imageKey="Hero" fallback={bengaliImages.hero} alt="Bengali food spread" fill priority sizes="100vw" className="absolute inset-0 -z-20 object-cover opacity-40" /><div className="absolute inset-0 -z-10 bg-[linear-gradient(90deg,rgba(16,24,17,.98),rgba(16,24,17,.5))]" /><Reveal className="mx-auto max-w-6xl"><p className="text-xs font-black uppercase tracking-[.2em] text-accent">The Bengali Food</p><h1 className="mt-5 max-w-3xl text-5xl font-black leading-[.94] sm:text-7xl">Bengali dishes, ready when you are.</h1><p className="mt-6 max-w-2xl text-lg leading-8 text-white/82">Explore a selection here, then open the live ordering menu for current availability and pickup or delivery.</p><OrderOnlineButton className="mt-8 inline-flex min-h-12 items-center justify-center rounded-lg bg-primary px-7 text-sm font-black text-[#142016]" label="Open live ordering menu" /></Reveal></section><section className="sticky top-[72px] z-30 border-y border-border bg-background/95 px-5 py-4 backdrop-blur"><nav aria-label="Menu categories" className="mx-auto flex max-w-6xl gap-2 overflow-x-auto">{menuCategories.map((category) => <a key={category.name} href={`#${category.name.toLowerCase().replaceAll(" ", "-").replaceAll("&", "and")}`} className="shrink-0 rounded-lg border border-border bg-surface px-5 py-3 text-sm font-black text-muted hover:text-white">{category.name}</a>)}</nav></section><ManagedMenuSections fallback={menuCategories} /><section className="px-5 pb-20 sm:px-6"><Reveal className="mx-auto max-w-6xl rounded-lg border border-primary/30 bg-primary/10 p-7"><h2 className="text-3xl font-black text-secondary">Prices and availability can change.</h2><p className="mt-2 max-w-2xl text-muted">The online menu has the current offerings, service options, and checkout.</p><OrderOnlineButton className="mt-5 inline-flex min-h-11 items-center justify-center rounded-lg bg-primary px-6 text-sm font-black text-[#142016]" label="Order online" /></Reveal></section></>;
}
